### ISSUE TITLE
Initial assessment of accuracy of LLM label information extraction and checklist evaluation

### ISSUE THREAD

**Issue by SamuelPelletierEvraire** [ai-cfia/harvester-prototype#1]
- [x] checkin test images (one product per folder) 
- [x] create input spreadsheet for checklist (confidential so not checked in)
  - [x] extract checklist into spreadsheet
  - [x] provide reformulate questions and key names for every question
  - [x] export to .csv as input to the script
- [x] iterate through product folders to generate LLM queries 
  - [ ] read input .csv and generate n queries per product
- [x] testing
  - [x] Testing with original checklist question
  - [x] Testing with the modified question
  - [x] Testing with different degree of certitude
  - [x] Testing with different way to ask question
- for each test run
  - [x] Output YYYY-mm-dd-result.json
  - [x]  Compile result to get % result of correct answers.
